### PR TITLE
https instead http for openstreetmap

### PR DESCRIPTION
**Pull request by predatell**

### CODE REVIEW

**Comment by predatell** [comment]
Why did you close this issue? If you use 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png' every page what has it is not secure. HTTPS page require all included links through https!

**Comment by caioariede** [comment]
@predatell I closed it because tests were failing. Do you think we could use `//` instead of hardcoding the scheme?

**Comment by predatell** [comment]
I am not sure... I'll try. I don't know why it failed tests. But it worked for me for long time... google provider can work with https, mapbox is also hardcoded with https: 'https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}'

**Comment by predatell** [comment]
You are right "//" this('//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png') works

**Pull request closed without merging**
