### PR TITLE
remove livequery; this make it working into wagtailadmin

### PR DESCRIPTION
**Pull request by fpoulain**
I add this PR, following #106 comments.

### CODE REVIEW

**Comment by fpoulain** [comment]
Actually I am more a javascript noobz than a javascript ninja, so:

1. I don't know if firering document.ready this way is orthodox.
1. I don't know if the removal of livequery allow to deal with complex setups (i.e. I guess that if `input[data-location-field-options]` is priorly modified in some way by some javascript during web form rendering, forms.js may fails to behave as we want).
1. Anyway, it works for me into Django admin (v2.0 iirc) and into Wagtail admin (v2.3).

**Comment by alantrick** [comment]
So I just noted a bug in this. I don't know if it's a regresion or if it existed before, but it only initializes the first location field on a page. The problem is that `$('input[data-location-field-options]')` will actually give you a collection of elements, but jquery is very sneaky about this.

Another comment is that if you have the field in an inline, and you add extra, it won't currently get initialized. You can get around this by using `$(document).on('formset:added', fn)`. There's an example at the bottom of https://gitlab.com/alantrick/django-adminstats/blob/master/django_adminstats/static/django_adminstats/chart_form.js

Aksi, `document.ready` should be unnecessary, because this javascript code is put after the relevant elements on the page.

**Comment by fpoulain** [comment]
I agree with those bugs, but I don't feel myself sufficiently comfortable with javascript to quickly refactor this code and address the bugs. That's why I mentioned this code as "works for me".

**Comment by caioariede** [comment]
Fixed in #114

**Pull request closed without merging**
